# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picrust',
            name='rRNACount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
