# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_picrust_rrnacount'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='soil_ACE_protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_active_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_agg_stability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_subsurf_hard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_surf_hard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_water_cap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
