# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0006_userprofile_dataid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTU_99',
            fields=[
                ('otuid', models.TextField(primary_key=True, serialize=False)),
                ('otuName', models.CharField(blank=True, max_length=90)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Class')),
                ('familyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Family')),
                ('genusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Genus')),
                ('kingdomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Kingdom')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Order')),
                ('phylaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Phyla')),
                ('speciesid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Species')),
            ],
        ),
        migrations.RemoveField(
            model_name='picrust',
            name='speciesid',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='whitelist_edit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='whitelist_view',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='picrust',
            name='otuid',
            field=models.ForeignKey(default='unclassified', on_delete=django.db.models.deletion.CASCADE, to='database.OTU_99'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='otuid',
            field=models.ForeignKey(default='unclassified', on_delete=django.db.models.deletion.CASCADE, to='database.OTU_99'),
            preserve_default=False,
        ),
    ]