# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20170214_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microbial',
            old_name='phosplipid_fatt_acid_concentration',
            new_name='phosplipid_fatt_acid_conc',
        ),
    ]
