# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20170223_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picrust',
            name='geneCount',
        ),
        migrations.AddField(
            model_name='picrust',
            name='geneList',
            field=models.TextField(blank=True),
        ),
    ]
