# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-26 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20170310_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refid',
        ),
    ]
