# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_remove_profile_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wip',
            field=models.BooleanField(default=False),
        ),
    ]
