# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-02 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_project_wip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='alignDB',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='taxonomyDB',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='templateDB',
        ),
    ]
