# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20170902_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='koOtuList',
            fields=[
                ('koID', models.TextField(primary_key=True, serialize=False)),
                ('otuList', models.TextField(blank=True)),
            ],
        ),
    ]
