# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_kootulist'),
    ]

    operations = [
        migrations.AddField(
            model_name='otu_99',
            name='otuSeq',
            field=models.TextField(blank=True),
        ),
    ]
