# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20180706_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kootulist',
            name='koID',
            field=models.TextField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
