# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-26 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0019_auto_20180730_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaymetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleIDs', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('yday', models.TextField(blank=True)),
                ('dayl', models.TextField(blank=True)),
                ('prcp', models.TextField(blank=True)),
                ('srad', models.TextField(blank=True)),
                ('swe', models.TextField(blank=True)),
                ('tmax', models.TextField(blank=True)),
                ('tmin', models.TextField(blank=True)),
                ('vp', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
