# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-05 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_daymetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='daymetdata',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privateProjectList',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daymetdata',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
