# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20190305_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='ace_soil_protein_index_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='active_carbon_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='aggregate_stability_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='k_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='minor_elements_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='organic_matter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='organic_matter_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='p_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='ph_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='repisration_four_day_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='respiration_four_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='root_pathogen_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='root_pathogen_pressure_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_texture_clay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_texture_sand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_texture_silt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='subsurface_hardness_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='surface_hardness_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='water_capacity_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
