# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-13 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20190321_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymetdata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recentRIDs',
            field=models.CharField(blank=True, default=b'', max_length=32),
        ),
        migrations.AlterField(
            model_name='daymetdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
