# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-30 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20190513_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soil',
            old_name='overall_rating',
            new_name='CASH_SHI_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='soil_ACE_protein',
            new_name='soil_ACE_protein_index',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='ace_soil_protein_index_rating',
            new_name='soil_ACE_protein_index_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='active_carbon_rating',
            new_name='soil_active_C_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='aggregate_stability_rating',
            new_name='soil_agg_stability_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='k_rating',
            new_name='soil_k_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='minor_elements_rating',
            new_name='soil_minor_elements_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='organic_matter',
            new_name='soil_organic_matter',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='organic_matter_rating',
            new_name='soil_organic_matter_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='ph_rating',
            new_name='soil_pH_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='p_rating',
            new_name='soil_p_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='respiration_four_day',
            new_name='soil_respiration_four_day',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='repisration_four_day_rating',
            new_name='soil_respiration_four_day_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='root_pathogen_pressure',
            new_name='soil_root_pathogen_pressure',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='root_pathogen_pressure_rating',
            new_name='soil_root_pathogen_pressure_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='soil_subsurf_hard',
            new_name='soil_subsurf_hardness',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='subsurface_hardness_rating',
            new_name='soil_subsurf_hardness_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='soil_surf_hard',
            new_name='soil_surf_hardness',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='surface_hardness_rating',
            new_name='soil_surf_hardness_rating',
        ),
        migrations.RenameField(
            model_name='soil',
            old_name='water_capacity_rating',
            new_name='soil_water_cap_rating',
        ),
    ]
