# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20190530_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymetdata',
            name='yday',
        ),
        migrations.RemoveField(
            model_name='daymetdata',
            name='year',
        ),
        migrations.AddField(
            model_name='daymetdata',
            name='tmean',
            field=models.TextField(blank=True),
        ),
    ]
