"""
Django settings for myPhyloDB project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8nj%u+=zh2v1wxebakh3w#_2!0o$h_@typk82%fte4op2d3b3q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ORM
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,   ### defaults to number of CPUs
    'timeout': 90,  ### number of seconds a worker is allowed to spend on a task before it is terminated.
    'retry': 120,   ### number of seconds a broker will wait for a cluster to finish a task (must be greater than task timeout)
    'queue_limit': 500, ### how many tasks are kept in memory by a single cluster
    'cpu_affinity': 3,  ### number of processors each worker can use (defaults to number of cpus)
    'bulk': 10,
    'orm': 'tasks',
}


#CACHES = {
#    'default': {
#        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#        'LOCATION': 'my_cache_table',
#    }
#}

# Application definition
INSTALLED_APPS = [
    'database',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
    'django_q',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myPhyloDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'database.views.usrFiles',
            ],
            'libraries': {
                'cache': 'django.templatetags.cache',
                'i18n': 'django.templatetags.i18n',
                'l10n': 'django.templatetags.l10n',
                'static': 'django.templatetags.static',
                'tz': 'django.templatetags.tz',
                'admin_list': 'django.contrib.admin.templatetags.admin_list',
                'admin_modify': 'django.contrib.admin.templatetags.admin_modify',
                'admin_static': 'django.contrib.admin.templatetags.admin_static',
                'admin_urls': 'django.contrib.admin.templatetags.admin_urls',
                'log': 'django.contrib.admin.templatetags.log',
            },
        },
    },
]

WSGI_APPLICATION = 'myPhyloDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.Microbe'),
    },
    'picrust': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.PICRUSt'),
    },
    'tasks': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.Tasks'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    #{ 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    #{ 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    #{ 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    #{ 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/myPhyloDB/media/'